betagouv/sante-psy

index.js, views/données-personnelles-et-gestion-des-cookies.ejs, views/partials/footer.ejs, views/suivi.ejs
Ajout des informations de Suivi d'audience et vie privée sur http://localhost:8080/suivi
Basé sur https://beta.gouv.fr/suivi/
Lien vers stats du site ajoutée : https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=160#?idSite=160&period=day&date=2021-02-11&segment=&category=Dashboard_Dashboard&subcategory=1
=> feat(tracking): add tracking info page

docker-compose.yml
Le container web peut potentiellement commencer avant la DB sans la config `depends_on`, on force l'ordre avec ces configs
Suppression de `link` comme 
> The --link flag is a legacy feature of Docker.
https://docs.docker.com/compose/compose-file/compose-file-v3/#links
https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on
=> docker: use depends_on to be sure DB is up before starting web server

controllers/appointmentsController.js, controllers/patientsController.js, index.js
Page title is displayed as tab title in browser, and is useful for users using screen readers (to navigate between tabs).
Make a separate page title for each page (except landing).
Example : landing page
vs. another page :
=> Make page titles more specific

controllers/dashboardController.js, controllers/loginController.js, index.js, package.json, utils/config.js, utils/cookie.js, utils/email.js
Source : https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
We use : 
- Set-Cookie : HttpOnly and Secure
- SameSite: Lax (strict breaks the login process when clicking a link from certain email clients, see comments in PR)
Note : we have two cookies : one is for sessions, one is for flash messages.
Todo, not in this PR : test logout
=> Feat : set security headers for cookies

test/dossier.json, utils/demarchesSimplifiees.js
Le champs département de demarches simplifiées était "value" et est maintenant "stringValue", toutes les données des psychologues ont `null` pour departement
Toutes les données seront mise à jour au prochain cron, sans problème :crossed_fingers:
=> fix(api): departement field changed from 'value' to 'stringField' 

static/js/build-psy-listing.js
If url starts with http, then display it as is. If not, then add // in front.
Either way, all urls should be clickable and go to the site.
=> Fix broken links in psylist, for real this time

cron_jobs/cron.js
Quand on deploie, les cron ne se lanceront qu'à partir de la règle du cronTime, ce qui peut se produire plusieurs heures aprés coup
Pour le job d'import complet de données, on souhaite qu'il se lance dès qu'on a un deploiement pour garantir la dernière fraicheur de données si la fonctionnalité en a besoin.
De la documentation du [npm cron](https://www.npmjs.com/package/cron)
> runOnInit - [OPTIONAL] - This will immediately fire your onTick function as soon as the requisite initialization has happened. This option is set to false by default for backwards compatibility.
=> Cron: import every data on deploy

static/js/build-psy-listing.js
Fix for a bug, where typing into a filter would replace all previous filters, so that you could only filter by one criteria at a time.
tests coming in separate PR
=> Fix : allow multiple filters in psylist

controllers/loginController.js
Lors du login d'un psychologue, nous utilisons seulement pour le fonctionnement de l'application son `id`, cette PR permet de sauvegarder seulement l'ID dans le cookie de session
RAS sur les sessions existantes
=> fix(cookie): use only id for psy

db/appointments.js, db/patients.js, migrations/20210315172126_patient_appointments_deletedstatus.js, test/helper/clean.js, test/test-dbAppointments.js
Pour garder une trace en cas d'audit nous ajoutons le champs booléan `deleted` dans la BD pour appointments et patients
=> Db: add deleted status to appointments and patients

scalingo-dev-seed.sh, scalingo.json, test/seed/fake_data.js
Mettre des données pour le 1er deploiement de chaque review app sur scalingo à base de `npm run seed`
Le script se base sur la présence d'une variable d'environnement :
* `SEED_FAKE_DATA_DATABASE=true`
> first-deploy: Executed after the first deployment of a review app or one-click app.
https://doc.scalingo.com/platform/app/app-manifest#deployment-hooks
=> containers: seeding database for dev environement containers first deployment only

index.js, package-lock.json, package.json
Par défaut "Session data is stored server-side." 
* https://github.com/expressjs/session/blob/master/README.md#store
> It will leak memory under most conditions, does not scale past a single process, and is meant for debugging and developing.
Logs qu'on peut trouver en production (ou en local)
```
2021-03-16 16:26:25.711108123 +0100 CET [web-2] Warning: connect.session() MemoryStore is not
2021-03-16 16:26:25.711116226 +0100 CET [web-2] designed for a production environment, as it will leak
2021-03-16 16:26:25.711146438 +0100 CET [web-2] memory, and will not scale past a single process.
```
Egalement, chaque reboot de servers fait perdre les sessions
> [ all your sessions will be lost on restart anyway.](https://github.com/expressjs/session/issues/81#issuecomment-53086251)
Stocker les …
=> feat(session): do not use memory storage but cookie storage

views/legalNotice.ejs
Enlève le numéro de téléphone de la DINUM, pour éviter que l'accueil ne reçoivent des appels non désirés (contact par email priviliègié)
=> legal: remove phone number - none available

.env.sample, cron_jobs/cron.js, index.js, package-lock.json, package.json, utils/config.js, utils/sentry.js
Permettre la surveillance d'erreurs côté backend avec le service Sentry
Toutes les messages reçus par la fonction `console.error` sont envoyées à Sentry
https://sentry.io/settings/betagouv-f7/projects/sante-psy-prod/keys/
Si la variable `SENTRY_DNS` est défini avec :
> Initializing Sentry for log level error and config: https:
Sinon
> Sentry was not initialized as SENTRY_DNS env variable is missing
Testé avec `npm start` et `node cron_jobs/cron.js`  avec des données remontées vers Sentry :heavy_check_mark:
=> ops: add log alert system 'sentry' to monitor production

utils/sentry.js
Suite à une refacto, une methode qui n'existait plus se faisait appeller ce qui empêchait le deploiement de l'application:
`TypeError: this.init is not a function`
* ajout du notifications de scalingo par email dans le cas d'échec de deploiement
=> fix(sentry): wrong method called

views/landing.ejs
Bonus: ajout d'une ancre HTML sur je suis un étudiant / psychologue
=> refacto(ui-landing): change psy space buttons / headings

views/dashboard.ejs, views/editPatient.ejs, views/login.ejs, views/newAppointment.ejs, views/partials/header.ejs, views/reimbursement.ejs
Fix for a bug where the psy pages menu was displaying in all pages.
Before : 
After :
=> Fix: no menu in public pages

controllers/loginController.js, test/test-loginController.js
L'email de login contient un token de 362 caractères en base 64 qui peut causer des problèmes avec certains fournisseurs d'email (outlook safelink), cette PR raccourcie ce token à 52 caractères hexadécimal
Bonus:  Cela facilite le copier coller du token à partir de l'email dans le cas où on ne peut pas cliquer sur les liens proposés
La coute durée de vie (1h) du token ainsi que sa suppresion une fois utilsé sont la sécurité de ce système :lock: 
Demarches simplifiées utilisent également de l'hexadécimal pour son token de connexion
https://www.ssi.gouv.fr/administration/precautions-elementaires/calculer-la-force-dun-mot-de-passe/
=> refacto: login token from 256 base 64 to 26 using hex

controllers/reimbursementController.js, views/partials/selectPayingUniversity.ejs
La page remboursement ne peut pas s'afficher si il n'y pas de données d'universités.
Ceci a été rencontré sur une review app de staging
Pour rendre l'application plus résiliente (accès à la facturation), on affiche la page "remboursement" avec un message d'erreur plutôt que de rediriger vers "mes séances"
=> fix: render reimbursement page even when no db is available

controllers/loginController.js, views/emails/login.ejs
Certains fournisseurs d'emails modifient les liens par mesure de protection et ne permettent pas de se connecter
> https://emea01.safelinks.protection.outlook.com/?NOTRE_LIEN
On propose un lien brute plutôt qu'un lien dans le lien secondaire de connexion
=> refacto: login email with secondary raw connexion link

controllers/dashboardController.js, test/test-dashboardController.js, views/editPatient.ejs, views/myPatients.ejs
Pour simplifier le formulaire des patients, le numéro INE est facultatif, et on s'appuie sur le champs booléen "isStudentStatusVerified" pour dire qu'on a bien affaire à un étudiant
Dans le dashboard les patients qui n'ont pas d'INE ne seront plus considérés comme dossier incomplet
=> feat: optional INE for patient

db/psychologists.js
Certains psy ont une avalanche de demandes qu'ils n'arrivent pas à absorber.
Il y a certes une demande elevée, mais afin d'aider à équilibrer cette charge parmis les psychologues, nous proposons de changer l'ordre d'apparition alphabétique en aléatoire pour - potentiellement - mieux distribuer la charge sur l'annuaire
=> feat: random order from psy list to balance psy contact from students

db/psychologists.js, test/test-dbPsychologists.js
Certains utilisateurs utilisent un email avec des majuscules pour se logguer, tous les emails étaient en lowercase en base, cela cause un mauvais match, les empechant de se connecter.
Cette PR compare les emails en lower case pour se logguer, mais utilise la même case pour envoyer l'email
=> fix(login): compare email in lowercase

cron_jobs/cron.js
ce cron ne fonctionne pas : https://crontab.guru/#0_8_1-7_*_1 cette PR propose d'utiliser un plus simple pour lancer le job de récapitulatif d'email seulement les 1er jour de chaque mois
https://crontab.guru/#0_8_1_*_*
=> fix(cron email): every first of the month

.gitignore, static/css/custom.css, views/faq.ejs
Fix sticky menu when scrolling all the way down
before:
after:
and fix menu display when in xs and sm:
before:
after:
=> Review faq responsivity

README.md, db/psychologists.js, test/test-dbUniversities.js
L'API DS ne nous retourne pas l'assignation de l'université pour un psy, car elle est seulement stockée dans PG. Ca veut dire que le CRON mettait tout le temps à jour l'assignedUniversityId - car pour lui la valeur n'existait pas.
Ce fix permet de seulement mettre assignedUniversityId pour les nouveaux cas (insert) - ceux qui sont déjà connus dans PG ne seront pas mis à jour (onConflict / merge)
=> fix(cron): do not update assignedUniversityId for a already existing psy

db/psychologists.js, test/test-dbPsychologists.js, test/test-reimbursementController.js
Bug sur le formulaire "remboursement de mes séances"
Lorsqu'on change d'université de rattachement, cela modifie l'ancien champs "declared uni id" au lieu de "d'assigned uni id"
=> fix: change assigned uni id instead of declared uni id

views/emails/summaryUniversity.ejs
Ajout de stats.santepsyetudiant.beta.gouv.fr/ dans l'email de récapitulatif de séances qui part tous les 1er de mois dans le cron [SendSummaryToUniversities,](https://github.com/betagouv/sante-psy/blob/main/cron_jobs/cron.js#L16-L21)
=> feat(emailUni): add dashboark link inside universities summary email

db/appointments.js, frontend/src/components/Psychologist/Appointments/NewAppointment.jsx, frontend/src/services/date.js
Envoi des dates du front vers le back en UTC comme c'était le cas avant la migration react.
Cela règle le problème des nouvelles séances déclarées mais une action devra être réalisée sur la base de données après le déploiement de cette PR afin de corriger les dates créées entre la migration react et cette PR : 
```
-- check the different timezone used to create appointments
select EXTRACT(HOUR from appointments."appointmentDate" at TIME zone 'UTC'), count(*), min("createdAt"), max("createdAt") from appointments 
group by EXTRACT(HOUR from appointments."appointmentDate" at TIME zone 'UTC');
-- for each timezone, add the missing hours to put them back in UTC timezone
update appointments 
set "appointmentDate" = "appointmentDate" + interval '4' HOUR
where EXTRACT(HOUR from …
```
=> Fix tableau récapitulatif si séance créée le premier jour du mois

scripts/matchSpecialPsyToUniversities.ts
If a psy has no assigned university yet, we had the following error: 
```
TypeError: Cannot read property 'name' of undefined
at /home/sricardo/dev/betagouv/sante-psy/scripts/matchSpecialPsyToUniversities.ts:55:81
```
=> Fix match psy to university script

db/psychologists.js, scripts/matchSpecialPsyToUniversities.ts, test/test-dbPsychologists.js
Archived psychologist also needs to be matched to correct university by the script `matchSpecialPsyToUniversities`. They may still declare appointments and need to send their invoices to the correct university.
=> Match archived psy to university

frontend/cypress/integration/header.spec.js, frontend/src/components/Header/Header.jsx
* Add link to go from psy space to public space and vice versa ("Accéder à mon espace" & "Revenir à l'accueil")
* Use router link for nav items
* Add more tests (& rework)
Note : on mobile, user needs to explicitly close the modal menu by clicking on "Fermer". Is that the wanted behavior from dsfr?
=> Add header link for connected user

migrations/20210806091509_use-date.ts, test/db/psychologists.spec.ts
With the current react date picker it's impossible to have a clean date (it always take in account the TZ of the user which we don't want)
solutions: 
- use another one (didn't look a lot but no obvious choice), it needs to be very customisable and allow to use a proper date at midnight GMT
- Create a react dsfr one (might me long...)
- keep it like that
=> Use date in db instead of datetime

.env.ci, .env.sample, utils/sentry.ts
Added new environment variable to setup a trace sample rate  to limit the number of calls to sentry.
there are too many calls and the server is quickly saturated.
=> Added new environment variable to setup a trace sample rate 
