betagouv/sante-psy

views/partials/footer.ejs
views/partials/header.ejs

Change name of ministry

---

views/partials/header.ejs

Pour faire remonter les statistiques de visite sur : https://stats.data.gouv.fr/

feat(tracking): add matomo

---

controllers/appointmentsController.js
controllers/patientsController.js
index.js
migrations/20210215163747_add-patient-table.js
static/css/custom.css
test/test-appointmentsController.js
utils/db.js
views/myAppointments.ejs
views/newAppointment.ejs
views/newPatient.ejs

Description
--------
Changements : 
- la page /nouvelle-seance propose maintenant de choisir un patient dans une liste. 
- on peut créer des patients dans /nouveau-patient (pas encore de page avec la liste des patients)
Démo
------
Modèles des tables:

New patient page

---

controllers/patientsController.js
views/newAppointment.ejs

On ajoute "Votre patient n'est pas dans la liste ?"

When creating an appointment with missing patient, direct user to createPatient

---

.husky/pre-push
README.md

Supprimer le hook de pre push lançant les tests

git hook: delete pre push

---

controllers/psyListingController.js
views/psyListing.ejs

Gérer les erreurs comment dans dashboardController (c'est mieux géré :stuck_out_tongue: ) pour psychologistController

refactor: apply the same logic as dashboardController to psychologistController

---

views/dashboard.ejs
views/myAppointments.ejs
views/myPatients.ejs
views/newAppointment.ejs
views/newPatient.ejs

Ajout de texte explicatif, simplification et harmonisation du html, ajustement des alignements et marges.
J'ai remis les boutons "Nouveau X" en haut des listes, parce que les listes sont triées avec le plus récent en haut, et parce que ca fait des blocs plus clairs visuellement je trouve. 
Dahsboard : 
Nouveau patient :
Nouvelle seance :

Display fixes before user test

---

views/psyListing.ejs

Afficher les prénoms et nom (plutôt que le champ Name seul)

fix: use lastName/firstnames instad of name

---

README.md

https://github.com/betagouv/sante-psy/tree/doc/readme#sant%C3%A9-psy--httpssantepsyetudiantsbetagouvfr

readme: add CI badge for main branch

---

index.js
views/landing.ejs

Ajout d'un redirection 404 lorsque la page n'existe pas

chores: add 404 redirection to index page with error display

---

controllers/appointmentsController.js

Une PR pour une type pour ne pas l'oublier :slightly_smiling_face:

typo: créé --> créée

---

views/dashboard.ejs
views/editPatient.ejs
views/login.ejs
views/myAppointments.ejs
views/myPatients.ejs
views/newAppointment.ejs
views/newPatient.ejs
views/partials/header.ejs

Use a different title in header for psy pages : 
And when you click the header, go to the main dashboard (/psychologues/mes-seances) rather than the public landing page.

Feat: header for psy pages

---

index.js
views/editPatient.ejs
views/myAppointments.ejs
views/myPatients.ejs
views/newAppointment.ejs

Fix: pre launch fixes

---

utils/config.js
views/landing.ejs
views/legalNotice.ejs
views/newAppointment.ejs

But
------
Enlevé l'écriture inclusive du site public.

Remove inclusive writing 

---

cron_jobs/importDataFromDS.js
db/psychologists.js
test/helper/clean.js
test/test-dbPsychologists.js
test/test-importDataFromDS.js
utils/config.js
views/emails/multipleAcceptedAlert.ejs

When a user has multiple dossiers in Demarches Simplifées that were accepted, send the team an email.

Feat: notify for multiple accepte dossiers

---

static/js/build-psy-listing.js
views/psyListing.ejs

Ajouter la possibilité de filtrer par département (numéro et nom)
La gestion des tirets et accents qui rendent difficile la selection de département comme le `Val-d'Oise`

feat: psy-list-by-departement

---

views/faq.ejs

Suggest changing browser if download is blocked

---

cron_jobs/cron.js
cron_jobs/cronDemarchesSimplifiees.js
db/dsApiCursor.js
test/helper/clean.js
test/test-cronDemarchesSimplifiees.js
test/test-dbDsApiCursor.js
test/test-dbPatients.js
test/test-dbPsychologists.js

On a observé que le cron job avait du mal à se relancer, c'est PR propose une autre méthode d'éxécution

fix(cron): change the way cron jobs are called

---

views/psyListing.ejs

Retour sur la plateforme, ajout de ce message sur l'annuaire psy

ui(help): indicate psy list is updated every day at least

---

controllers/patientsController.js
db/patients.js
migrations/20210311092126_doctor-patient-info.js
test/test-appointmentsController.js
test/test-dashboardController.js
test/test-dbPatients.js
test/test-patientsController.js
views/editPatient.ejs

l'ajout de l'information du médecin ou SSU orientant le patient vers le psychologue

Feat: add doctor info to patient table

---

views/landing.ejs

Ajouter les numéros devant les étapes sur le "comment ça marche ?".

Fix Adding step numbers

---

views/editPatient.ejs

Pour le formulaire d'ajout de patient

refacto(patient): add required to html input and max-length for INE

---

controllers/loginController.js

Email normalization does a lot of weird things : see "normalizeEmail" in https://github.com/validatorjs/validator.js#sanitizers
In particular it removes dots in gmail adresses : aaa.bbb@gmail.com is normalized to aaabbb@gmail.com (which is an unknown adress for us). 
This is breaking login for gmail adresses with dots in them.
In another PR, we could look at lowercasing emails... But first we have to check the emails in db are all lowercase, so it's not trivial (other PR)

Remove email normalization

---

views/faq.ejs
views/landing.ejs

Explain student eligibility better

---

controllers/loginController.js
test/test-appointmentsController.js
test/test-dashboardController.js
test/test-patientsController.js
test/test-redirect404.js
utils/cookie.js

fix(cookie): use directly psychologist as the object returning the id

---

controllers/appointmentsController.js
controllers/loginController.js
controllers/logoutController.js
controllers/patientsController.js
utils/logs.js

Ajout de plus de logs pour permettre un audit:
* creation
* suppression
* mise à jour
* login

logs: add logs when creating/updating/deleting/logging

---

controllers/loginController.js

Indiquer à l'utilisateur si son email est inconnu, classé sans suite ou refusé sur DS lors du login

feat(login): notify when email is unknown

---

views/faq.ejs

Removed a word that appeared twice

Removed duplicate

---

static/js/build-psy-listing.js

Enlever les // en trop dans les emails

Fix: Remove slash in mail

---

views/psyListing.ejs

Il manquait un fil d'ariane sur la page de l'annuaire.

Fix : Adding ariane on the psy listing page

---

.env.sample
controllers/loginController.js
docker-compose-for-ci-github-csrf.yml
docker-compose-for-ci-github.yml
docker-compose-only-db.yml
docker-compose.yml
utils/config.js
utils/logs.js

Use specific secret salt for hashed **logs**
:warning: this PR adds a new environment variables : `SECRET_LOGS` it was added to :

logs: hash with a different salt

---

test/test-graphql.js
utils/graphql.js

L'API DS nous a renvoyé des erreurs que l'import n'a pas su parser, le code simplifie la lecture d'erreur en logguant directement puis en parsant l'array d'erreurs si il existe
> ERROR: Could not import DS API data to PG TypeError: Cannot read property 'errors' of undefined

fix(api): error parsing from DS cannot be read and raise errors

---

README.md

Added some syntax highlighting in the README (docker doesn't support inline comments) + command prompt $ to distinguish between command line & code

Markdown improvements

---

db/psychologists.js
test/test-dbPsychologists.js

feat(psyList): add french language if missing

---

controllers/appointmentsController.js
test/test-appointmentsController.js

Ajout d'une verification sur le patient id lors de la création d'une séance par un psychologue

fix(appointments): validate patient id is linked to psy id

---

views/landing.ejs

refacto(ui-landing): shorter sentence and bigger font for 2nd sentence

---

index.js
views/landing.ejs

Bonus: changer "en savoir plus" à "consulter la foire aux questions" partout

refacto(ui-landing): find a psychologist button set to primary

---

views/landing.ejs

Remarqué par Valentine :slightly_smiling_face:

typo(french): pouvez --> pourrez

---

views/faq.ejs

mobile: change arrow size to fit on mobile

---

views/landing.ejs

Les medecins ne semblent pas trouver leur information sur le site, cette PR ajoute une phrase les concernant

landing: add sentence for doctor to check the FAQ

---

controllers/reimbursementController.js
db/psychologists.js
db/universities.js
index.js
migrations/20210324185600_add-isConventionSigned.js
static/js/selectPayingUniversity.js
test/helper/clean.js
test/seed/fake_data.js
test/test-dbPsychologists.js
test/test-reimbursementController.js
views/partials/selectPayingUniversity.ejs
views/reimbursement.ejs

Pour mettre en prod :
-----
Première visite, les champs sont vides en DB, je vois un formulaire pour les remplir : 
Il y a une option "Aucune pour le moment" (dans la db, c'est une université dont le nom est "--- Aucune pour le moment". Ca permettra de faire des stats sur les psys qui n'ont pas eu de contact du tout)
Modifs enregistrées :
Quand on selectionne "aucune" :

Feat: specify payingUniversityId and isConventionSigned

---

views/dashboard.ejs
views/partials/selectPayingUniversity.ejs
views/reimbursement.ejs

Mise à jour du texte, pour reprendre celui qu'on envoie dans le mail à tous les psys, puisqu'on a changé de stratégie de remboursement.
+ petites modifs suggérées par Valentine.

Fix: update text about reimbursement

---

controllers/dashboardController.js
controllers/patientsController.js
static/css/custom.css
test/helper/clean.js
test/seed/fake_data.js
test/test-dashboardController.js
test/test-patientsController.js
views/editPatient.ejs
views/myPatients.ejs

La liste des patients pour une psychologue peut devenir longue, et il devient difficile de voir pour qui il manque des informations obligatoires pour obtenir un remboursement
Ajouter une idée visuelle pour indiquer les patients dont le dossier n'est pas encore complet (INE manquant par exemple)
* https://gouvfr.atlassian.net/wiki/spaces/DB/pages/310706305/Tag
* https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222331396/Ic+nes+-+Icons#Actions
* https://gouvfr.atlassian.net/wiki/spaces/DB/pages/217186370/Couleurs+-+palette

feat(myPatients): add patient folder completed status

---

static/js/datepicker-fr.js

Description
--------
Le calendrier des séances doit commencer début mars et ne doit pas aller au delà de fin décembre 2021.

fix : Change range of the appointment's calendar

---

views/dashboard.ejs
views/partials/billing.ejs

text: clarify reimbursement process

---

controllers/loginController.js
index.js

On va changer l'email de contact pour un nouvel email qu'on va envoyer dans Crisp. Comme ca on garde l'email existant pour continuer la communication avec les SSU sans changement.

Make contact email configurable : use value from config.js

---

views/partials/header.ejs

Ajout d'un bouton déconnexion sur le header principal
Qui ramène vers la page login

feat: add logout button

---

utils/demarchesSimplifiees.js

Fix this annoying bug where the alphabetical order is messed up because some names start with a space :

Trim strings in DS import

---

static/js/build-psy-listing.js

Display 20 results per page instead of 10.

PsyListing : 20 results per page

---

controllers/patientsController.js
db/patients.js
migrations/20210419152935_student-number-constraint.js
package-lock.json
test/test-dbPatients.js
test/test-patientsController.js
utils/validation.js

Certains étudiants n'ont pas de numéro étudiants à 11 caractères (en général une dizaine de chiffres), il faut enlever cette contrainte

refacto: student number can be other than 11 chars - but max 50 chars

---

views/dashboard.ejs
views/faq.ejs
views/landing.ejs
views/login.ejs
views/myAppointments.ejs
views/myPatients.ejs
views/partials/section.ejs
views/psyListing.ejs

Depuis la migration 0.0.4 vers 1.0.0, quelques soucis ont émergés : 
* mobile
* l'annuaire (container cassé et ariane bizarre)
* des paddings / margin 
Cette PR a pour but de corriger ces regressions

fix: view landing / psylist

---

README.md
db/universities.js
migrations/20210422132727_add_email_to_universities.js
scalingo-dev-seed.sh
scripts/insertEmailToUniversities.js
scripts/insertUniversities.js
test/seed/test-ssu-renew.csv

But 
--------
Récupérer les adresses mails des universités et des SSU répertoriés à la main et les ajouter dans la base sur l'université correspondante.
Voir https://github.com/betagouv/sante-psy/tree/feat/script-adding-universities-emails#ins%C3%A9rer-les-universit%C3%A9s-pour-la-production

Adding SSU and universities email from file

---

README.md
controllers/dashboardController.js
docker-compose.yml
utils/config.js
views/dashboard.ejs
views/partials/announcement.ejs

Ajouter la possibilité d'afficher des annonces par une variable d'environnement "ANNOUNCEMENT" sur Scalingo
La variable a déjà été modifiée sur la production
https://github.com/betagouv/audioconf/pull/120

feat: add announcement via a env variable

---

scalingo-dev-seed.sh
views/faq.ejs
views/landing.ejs
views/psyListing.ejs

Pour améliorer la compréhension du dispositif au près des étudiants, on ajoute explicitement que n'importe quel étudiant peut contacter n'importe quel psychologue **partenaire** peu importe sa région ou université d'origine

update: student can contact any psychologists listed, even if they are not from the same area

---

test/test-dashboardController.js

We left a describe.only in the code. Removing it.

fix(test): remove only

---

.github/workflows/nodejs.yml
package-lock.json
package.json

Local: ![image](https://user-images.githubusercontent.com/5389328/116898631-e8454f80-ac36-11eb-83ad-e7d0bc4a1b41.png)
Github:

Add a linter check on ejs files

---

controllers/reimbursementController.js
db/appointments.js
test/test-dbAppointments.js
test/test-reimbursementController.js

Related to sentry error: 
https://sentry.io/organizations/betagouv-f7/issues/2374702697/?project=5682189&query=is%3Aunresolved

Fix reimbursement when patients but no appointments

---

test/seed/fake_data.js

Clean db before seeding it

---

docker-compose.yml

Fix https://github.com/betagouv/sante-psy/issues/152

fix: npm install needs to be done inside the docker container

---

views/partials/header.ejs

Fix menu responsivity

---

db/universities.js
scripts/departementToUniversityName.js

Ajout de l'université de Valenciennes pour les candidats du 59

chore: add valenciennes university

---

controllers/loginController.js
db/psychologists.js
frontend/cypress/integration/login.spec.js
frontend/cypress/integration/redirection.spec.js
frontend/cypress/integration/utils/login.js
frontend/src/App.jsx
frontend/src/components/Header/Header.jsx
frontend/src/components/Header/Menu.jsx
frontend/src/components/Header/TopMenu.jsx
frontend/src/components/Login/Login.jsx
frontend/src/services/agent.js
frontend/src/stores/userStore.js
index.ts
package-lock.json
package.json
test/test-appointmentsController.js
test/test-dbPsychologists.js
test/test-jwt.js
test/test-loginController.js
test/test-patientsController.js
test/test-reimbursementController.js
utils/jwt.js

Remove personnal info from the token
Make sur the token is still valid when connecting, if not display an error message
Prepare the front to display welcome message to a connected user

Issue #158 - Better token management

---

utils/demarchesSimplifiees.js

https://sentry.io/organizations/betagouv-f7/issues/2424585028/?project=5682189&query=is%3Aunresolved

No psy found is not an error anymore

---

frontend/cypress/integration/appointments.spec.js
frontend/cypress/integration/patients.spec.js
frontend/src/components/Psychologist/Appointments/Appointments.jsx
frontend/src/components/Psychologist/Reimbursement/Billing.jsx

No convention message is now orange
Facturation items are now on top of the page for better visibility

Improve elements visibility

---

README_api_santé.md

Doc on how to build the API, and how to query it.
(not sure if this is the final version of the API, but this is the first version that WORKS! :D )

README file for API santé

---

cron_jobs/cronUniversityPayments.ts
db/universities.js
test/test-dbUniversities.js
views/emails/summaryUniversity.ejs

Update summary mail to universities

---

frontend/src/App.jsx
frontend/src/PsychologistRouter.jsx
index.ts
package-lock.json
package.json

So now with compression we have only 433kb to load !

Improve bundle sizes

---

README.md
services/demarchesSimplifiees/autoAccept.js

Cron jobs are run from the dist folder :/

Upload correct file

---

frontend/src/components/Login/Login.jsx
frontend/src/components/Psychologist/Appointments/Appointments.jsx
frontend/src/components/Psychologist/Appointments/NewAppointment.jsx
frontend/src/components/Psychologist/Patients/AddEditPatient.jsx
frontend/src/components/Psychologist/Patients/PatientRow.jsx
frontend/src/components/Psychologist/Profile/ConventionForm.jsx
frontend/src/components/Psychologist/Profile/EditProfile.jsx

Note that submit buttons are not working anymore with that...

Use Button instead of button

---

frontend/src/components/Faq/Faq.jsx
frontend/src/components/Page/Page.jsx
frontend/src/components/Page/page.cssmodule.scss

* Add a page component as base for faq, annuaire, mentions légales, etc.
* Example done for faq.

Page component

---

frontend/cypress/integration/psyListing.spec.js
frontend/src/components/Faq/Faq.jsx
frontend/src/components/PsyListing/PsyTable.jsx
frontend/src/components/PsyListing/PublicPsychologistProfile.jsx
frontend/src/components/PsyListing/publicPsychologistProfile.cssmodule.scss
frontend/src/services/string.js

... and add some spacing
May conflict with #322

Review public psy profile title & description

---

.env.ci
.env.sample
README.md
controllers/loginController.ts
cron_jobs/cronDemarchesSimplifiees.ts
cron_jobs/cronUniversityPayments.ts
docker-compose.yml
test/controllers/loginController.spec.js
test/test-cronDemarchesSimplifiees.js
utils/config.js
utils/email.ts

Env variables needs to be modified on scalingo... think about a proper way to do that in prod

Active ssl for email

---

controllers/universityController.ts
cron_jobs/cronUniversityPayments.ts
db/psychologists.ts
db/universities.js
scripts/insertEmailToUniversities.js
scripts/insertUniversities.js
scripts/matchSpecialPsyToUniversities.ts

TEST
La liste est ordonnée uniquement quand on doit l'afficher. Sinon elle ne l'est pas.
Liste des endroits ou getAll est utilisé : 
- const sendMailToUniversities ( cron_jobs/cronUniversityPayements.ts ).
- const upsertMany ( db/psychologists.ts ).
- const insertEmailToUniversities ( scripts/insertEmailToUniversities.js ).
- const runInsert ( scripts/insertUniversities.js ).
- const matchPsyToUni ( scripts/matchSpecialPsyToUniversities.ts )
Liste des endroits ou getAllByName est utilisé : 
- const getAll ( controllers/universityController.ts ) 
Peut-être changer le nom de la const en getAllByName pour le coup.

Order universities only if needed

---

controllers/conventionController.ts
db/universities.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/Psychologist/Profile/ConventionForm.jsx
test/controllers/conventionController.spec.ts
test/db/universities.spec.ts

Waiting for a react-dsfr update to manage isDisabled on radio button

Prevent user to sign convention with no university

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Faq/FaqTab.jsx

Waiting for react-dsfr onClick props on accordion

Add a matomo event on faq items

---

frontend/src/components/Psychologist/Appointments/ConventionModal.jsx

Add space in the convention modal

---

frontend/cypress/integration/appointments.spec.js
frontend/cypress/integration/contact.spec.js
frontend/cypress/integration/conventionModal.spec.js
frontend/cypress/integration/login.spec.js
frontend/cypress/integration/patients.spec.js
frontend/cypress/integration/profile.spec.js
frontend/src/components/Notification/Announcement.jsx
frontend/src/components/Notification/GlobalNotification.jsx
frontend/src/components/Notification/Notification.jsx
frontend/src/components/Notification/notification.cssmodule.scss
frontend/src/components/PsyListing/PublicPsychologistProfile.jsx
frontend/src/components/Psychologist/Appointments/Appointments.jsx
frontend/src/stores/commonStore.js

For now =>
keeping color of the page and normal font-weight => poll in matermost to check if we change it or not ?

Use dsfr alert for notification

---

utils/csp-config.ts

Fix matomo connection

---

frontend/cypress/integration/patients.spec.js
frontend/src/PsychologistRouter.jsx
frontend/src/components/Page/Page.jsx
frontend/src/components/Psychologist/Appointments/Appointments.jsx
frontend/src/components/Psychologist/Patients/Patients.jsx
frontend/src/components/Psychologist/Reimbursement/Billing.jsx

- callouts moved below alerts (it's not part of the page but depends of the content of the page)
- incomplete student alert has been removed

Better order between alerts & callouts

---

controllers/psyProfileController.ts
db/psychologists.ts
scripts/insertCoordinatesToPsychologists.ts
services/getAddressCoordinates.ts
test/db/psychologists.spec.ts
test/helper/clean.ts
test/services/updatePsyFields.spec.ts
types/Coordinates.ts

Knex throws an error if `coord = {}`

Fix insert coordinates script

---

frontend/src/components/PsyListing/PsyTable.jsx
frontend/src/components/PsyListing/psyTable.cssmodule.scss

a merger apres https://github.com/betagouv/sante-psy/pull/412

Improve pagination position

---

controllers/conventionController.ts
controllers/universitiesController.ts
db/psychologists.ts
db/universities.ts
frontend/cypress/integration/conventionModal.spec.js
frontend/cypress/integration/header.spec.js
frontend/cypress/integration/profile.spec.js
frontend/cypress/integration/utils/login.js
frontend/cypress/integration/utils/psychologist.js
frontend/src/PsychologistRouter.jsx
frontend/src/components/Psychologist/Profile/ConventionForm.jsx
frontend/src/components/Psychologist/Profile/PayingUniversity.jsx
frontend/src/services/agent.js
routers/universities.ts
services/updatePsyFields.ts
test/controllers/conventionController.spec.ts
test/controllers/universityController.spec.ts
test/db/psychologists.spec.ts
test/db/universities.spec.ts
test/helper/clean.ts
test/services/updatePsyFields.spec.ts
types/Psychologist.ts

Psy cannot change assignedUniversity anymore

---

README.md
scripts/matchPsyToUniversities.ts
scripts/matchSpecialPsyToUniversities.ts

Still something that needs to be confirmed about department which change university assignment by the past.

Clean assigned university

---

controllers/loginController.ts
controllers/psyListingController.ts
controllers/psyProfileController.ts
db/psychologists.ts
frontend/cypress/integration/profile.spec.js
frontend/src/components/PsyListing/PsyListing.jsx
frontend/src/components/PsyListing/PsyTable.jsx
frontend/src/components/PsyListing/PublicPsychologistProfile.jsx
frontend/src/components/Psychologist/Profile/EditProfile.jsx
frontend/src/components/Psychologist/Profile/PsyProfile.jsx
frontend/src/services/agent.js
frontend/src/services/search.js
frontend/test/search.spec.js
migrations/20210913064936_addresses.ts
services/demarchesSimplifiees/parsePsychologists.ts
services/updatePsyFields.ts
test/controllers/loginController.spec.ts
test/controllers/psyListingController.spec.ts
test/controllers/psyProfileController.spec.ts
test/cron_jobs/cronDemarchesSimplifiees.spec.ts
test/db/psychologists.spec.ts
test/db/universities.spec.ts
test/helper/create.ts
test/services/parsePsychologists.spec.ts
test/services/updatePsyFields.spec.ts
types/Psychologist.ts

Needs to be merged after https://github.com/betagouv/sante-psy/pull/416

Manage two addresses for psy

---

scripts/insertCoordinatesToPsychologists.ts
utils/validation.ts

* Handle only psychologists without coordinates (instead of all)
* Update log level of form check errors (to avoid logging it on production)

Update location script

---

cron_jobs/cronStudents.ts

to avoid tipimail timeout issue

fix: send student mails synchronously

---

utils/config.ts
utils/email.ts

**Merge only after tipimail conf change !**

conf(email): use subdomain to send emails

---

scripts/removePsyPersonalData.ts

Pour le lancer : `ts-node scripts/removePsyPersonalData.ts [dossierNumber]`
(En local, attached to sante-psy_web: `./node_modules/ts-node/dist/bin.js scripts/removePsyPersonalData.ts [dossierNumber]`)

feat(script): remove psy personal data

---

frontend/cypress/e2e/patients.cy.js
frontend/src/components/Psychologist/Appointments/Appointments.jsx
frontend/src/components/Psychologist/Appointments/NewAppointment.jsx
frontend/src/components/Psychologist/Patients/PatientStatus.jsx
frontend/src/components/Psychologist/Patients/Patients.jsx
frontend/src/services/date.js

feat(patients): add nb appointment in current year

---

services/demarchesSimplifiees/autoAccept.ts
test/services/autoAcceptPsychologist.spec.ts
utils/config.ts
utils/configDS/autoAcceptMessage.ts

La variable d'environnement a déjà été ajoutée en production.

feat(auto accept): update message

---

frontend/src/services/faq/psychologue/reimbursement.js

Removed FAQ question about session duration

feat: removed faq question about session duration

---

controllers/appointmentsController.ts
frontend/cypress/e2e/appointments.cy.js
frontend/cypress/e2e/conventionModal.cy.js
frontend/cypress/e2e/header.cy.js
frontend/cypress/e2e/reimbursement.cy.js
frontend/src/components/Psychologist/Appointments/Appointments.jsx
frontend/src/services/agent.js
frontend/src/services/date.js
routers/appointments.ts
services/appointments.ts
services/getBadges.ts
test/controllers/appointmentsController.spec.ts
utils/date.ts

The psychologist can see badges on the list of his appointments to see the first, the 8th and exceeded appointments

added badges to the list of appointments

---

controllers/psyProfileController.ts
db/psychologists.ts
migrations/20250630101101_update_description_field_to_text.ts
services/getAddressCoordinates.ts

- Added logs
- some fields are too long and trigger errors
- updated code to avoid api limit restrictions on getAddressCoordinates

FIX / import DS To PG
